"""
[Architecture Point: Application Layer - Service]
비즈니스 로직과 외부 서비스 오케스트레이션을 담당하는 서비스 계층입니다.
"""
import io
import os
import logging
from uuid import UUID
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from typing import List, Dict, Any

# ReportLab 임포트 추가
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

logger = logging.getLogger(__name__)

# 크로스 플랫폼 한글 폰트 Fallback 등록 엔진
font_paths = [
    "/usr/share/fonts/noto/NotoSansCJK-Regular.ttc",          # Alpine Linux CJK Regular
    "/usr/share/fonts/truetype/nanum/NanumGothic.ttf",        # Linux NanumGothic
    "C:/Windows/Fonts/malgun.ttf",                            # Windows MalgunGothic
    "C:/Windows/Fonts/gulim.ttc",                             # Windows Gulim Fallback
    "/System/Library/Fonts/Supplemental/AppleGothic.ttf",     # macOS AppleGothic
]

loaded_font = False
for path in font_paths:
    if os.path.exists(path):
        try:
            pdfmetrics.registerFont(TTFont("KoreanFont", path))
            logger.info(f"Successfully registered Korean font: {path}")
            loaded_font = True
            break
        except Exception as e:
            logger.warning(f"Failed to register font {path}: {e}")

if not loaded_font:
    logger.error("No Korean font registered. PDF may have character encoding errors.")


class ExportService:
    def generate_docx(self, project: Dict[str, Any], characters: List[Dict[str, Any]], events: List[Dict[str, Any]]) -> io.BytesIO:
        logger.info(f"Executing generate_docx for project_id: {project.get('id')}...")
        try:
            doc = Document()
            
            # 1. 제목 (Title)
            title_para = doc.add_paragraph()
            title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = title_para.add_run(project.get("title", "무제 프로젝트"))
            run.bold = True
            run.font.size = Pt(24)
            
            doc.add_paragraph()
            
            # 2. 로그라인 (Logline)
            doc.add_heading("01. 로그라인", level=1)
            p_log = doc.add_paragraph()
            p_log.add_run(project.get("logline", "내용 없음")).italic = True
            p_log.paragraph_format.left_indent = Pt(20)
            
            doc.add_paragraph()

            # 3. 기획의도 (Intended Purpose)
            doc.add_heading("02. 기획의도", level=1)
            doc.add_paragraph(project.get("intended_purpose", "내용 없음"))
            
            doc.add_paragraph()

            # 4. 등장인물 (Characters)
            doc.add_heading("03. 등장인물", level=1)
            for char in characters:
                p = doc.add_paragraph(style='List Bullet')
                run = p.add_run(f"{char['name']}")
                run.bold = True
                if char.get('role'):
                    p.add_run(f" ({char['role']})")
                
                p2 = doc.add_paragraph(char.get('description', ""), style='Normal')
                p2.paragraph_format.left_indent = Pt(20)

            doc.add_paragraph()

            # 5. 전체 줄거리 (Full Synopsis)
            doc.add_heading("04. 전체 줄거리", level=1)
            doc.add_paragraph(project.get("full_synopsis", "내용 없음"))
            
            doc.add_paragraph()

            # (부록) 상세 플롯 타임라인
            doc.add_heading("별첨. 전체 플롯 타임라인", level=2)
            for event in events:
                p_ev = doc.add_paragraph()
                p_ev.add_run(f"[{event.get('time_hint', '사건')}] ").bold = True
                p_ev.add_run(event.get('title', '무제'))
                
                p_ev_content = doc.add_paragraph(event.get('content', ""))
                p_ev_content.paragraph_format.left_indent = Pt(15)

            # 푸터
            doc.add_paragraph()
            footer = doc.add_paragraph(f"Generated by Scriptly on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
            footer.alignment = WD_ALIGN_PARAGRAPH.RIGHT
            
            target = io.BytesIO()
            doc.save(target)
            target.seek(0)
            return target
        except Exception as e:
            logger.error(f"Error in generate_docx: {e}", exc_info=True)
            raise

    def generate_pdf(self, project: Dict[str, Any], characters: List[Dict[str, Any]], events: List[Dict[str, Any]]) -> io.BytesIO:
        logger.info(f"Executing generate_pdf for project_id: {project.get('id')}...")
        try:
            buffer = io.BytesIO()
            # SimpleDocTemplate을 사용하여 PDF 정의
            doc = SimpleDocTemplate(
                buffer,
                rightMargin=54, leftMargin=54,
                topMargin=54, bottomMargin=54
            )
            
            # 스타일 시트 초기화 및 폰트 세팅
            styles = getSampleStyleSheet()
            
            # 한글 폰트가 등록되어 있으면 KoreanFont를 쓰고, 없으면 기본 Helvetica를 사용
            font_name = "KoreanFont" if loaded_font else "Helvetica"
            
            title_style = ParagraphStyle(
                name="KoTitle",
                parent=styles['Heading1'],
                fontName=font_name,
                fontSize=26,
                leading=32,
                alignment=1, # Center
                spaceAfter=30,
                textColor=colors.HexColor("#1e1b4b") # 어두운 남색
            )
            
            h1_style = ParagraphStyle(
                name="KoH1",
                parent=styles['Heading2'],
                fontName=font_name,
                fontSize=15,
                leading=19,
                spaceBefore=18,
                spaceAfter=8,
                textColor=colors.HexColor("#b45309") # 브라운/오렌지 계열
            )
            
            body_style = ParagraphStyle(
                name="KoBody",
                parent=styles['Normal'],
                fontName=font_name,
                fontSize=10,
                leading=15,
                spaceBefore=4,
                spaceAfter=4,
                textColor=colors.HexColor("#27272a") # 어두운 회색
            )
            
            bullet_style = ParagraphStyle(
                name="KoBullet",
                parent=body_style,
                leftIndent=15,
                firstLineIndent=-10,
                spaceAfter=6
            )
            
            indent_style = ParagraphStyle(
                name="KoIndent",
                parent=body_style,
                leftIndent=15,
                spaceBefore=2,
                spaceAfter=2,
                textColor=colors.HexColor("#4b5563") # 약간 밝은 회색
            )
            
            footer_style = ParagraphStyle(
                name="KoFooter",
                parent=styles['Normal'],
                fontName=font_name,
                fontSize=8,
                leading=10,
                alignment=2, # Right
                textColor=colors.HexColor("#9ca3af")
            )
            
            story = []
            
            # 1. 대제목 (Cover/Title)
            story.append(Spacer(1, 40))
            story.append(Paragraph(project.get("title", "무제 프로젝트"), title_style))
            story.append(Spacer(1, 20))
            
            # 2. 로그라인 (Logline)
            story.append(Paragraph("01. 로그라인 (Logline)", h1_style))
            logline_text = project.get("logline", "") or "등록된 로그라인이 없습니다."
            story.append(Paragraph(f"<i>&ldquo;{logline_text}&rdquo;</i>", body_style))
            story.append(Spacer(1, 10))
            
            # 3. 기획의도 (Intended Purpose)
            story.append(Paragraph("02. 기획의도 (Intended Purpose)", h1_style))
            purpose_text = project.get("intended_purpose", "") or "등록된 기획의도가 없습니다."
            # 줄바꿈 HTML 변환
            purpose_html = purpose_text.replace('\n', '<br/>')
            story.append(Paragraph(purpose_html, body_style))
            story.append(Spacer(1, 10))
            
            # 4. 등장인물 (Characters)
            story.append(Paragraph("03. 등장인물 (Characters)", h1_style))
            if characters:
                for char in characters:
                    char_desc = char.get("description", "") or "설명 없음"
                    char_desire = char.get("desire", "") or char.get("internal_desire", "") or "욕망 미설정"
                    role_str = f"({char.get('role', '조연')})" if char.get('role') else ""
                    occupation_str = f" - {char['occupation']}" if char.get('occupation') else ""
                    
                    story.append(Paragraph(
                        f"• <b>{char['name']}</b> {role_str}{occupation_str}",
                        bullet_style
                    ))
                    story.append(Paragraph(
                        f"내면의 욕망: {char_desire}",
                        indent_style
                    ))
                    story.append(Paragraph(
                        f"상세 설정: {char_desc}",
                        indent_style
                    ))
                    story.append(Spacer(1, 5))
            else:
                story.append(Paragraph("등록된 등장인물이 없습니다.", body_style))
            story.append(Spacer(1, 10))
            
            # 5. 전체 줄거리 (Full Synopsis)
            story.append(Paragraph("04. 전체 줄거리 (Full Synopsis)", h1_style))
            synopsis_text = project.get("full_synopsis", "") or "등록된 시놉시스가 없습니다."
            synopsis_html = synopsis_text.replace('\n', '<br/>')
            story.append(Paragraph(synopsis_html, body_style))
            story.append(Spacer(1, 15))
            
            # Page Break for Plot Timeline
            story.append(PageBreak())
            
            # 6. 별첨. 전체 플롯 타임라인
            story.append(Paragraph("별첨. 에피소드 플롯 타임라인", h1_style))
            story.append(Spacer(1, 10))
            if events:
                for idx, event in enumerate(events):
                    time_hint = f"[{event.get('time_hint')}]" if event.get('time_hint') else f"[사건 {idx+1}]"
                    title = event.get('title', '사건 제목 없음')
                    content = event.get('content', '') or '상세 서사가 등록되지 않았습니다.'
                    
                    story.append(Paragraph(
                        f"<b>{time_hint} {title}</b>",
                        body_style
                    ))
                    story.append(Paragraph(
                        content.replace('\n', '<br/>'),
                        indent_style
                    ))
                    story.append(Spacer(1, 6))
            else:
                story.append(Paragraph("등록된 플롯 사건 타임라인이 없습니다.", body_style))
                
            story.append(Spacer(1, 30))
            
            # 푸터
            generation_time = datetime.now().strftime('%Y-%m-%d %H:%M')
            story.append(Paragraph(f"Generated by Scriptly on {generation_time}", footer_style))
            
            # 빌드 실행
            doc.build(story)
            buffer.seek(0)
            return buffer
        except Exception as e:
            logger.error(f"Error in generate_pdf: {e}", exc_info=True)
            raise

    def generate_script_docx(self, title: str, html_content: str) -> io.BytesIO:
        """대본 HTML을 파싱하여 정밀하게 서식화된 Word (.docx) 문서를 생성합니다."""
        from bs4 import BeautifulSoup
        import re
        from docx.shared import Inches, Pt

        logger.info(f"Generating script DOCX for: {title}")
        doc = Document()

        # A4 여백 설정 (상하좌우 20mm, 약 0.8인치)
        for section in doc.sections:
            section.top_margin = Inches(0.8)
            section.bottom_margin = Inches(0.8)
            section.left_margin = Inches(0.8)
            section.right_margin = Inches(0.8)

        # 기본 글꼴 설정 (바탕체)
        style = doc.styles['Normal']
        style.font.name = 'Batang'
        style.font.size = Pt(11)

        # HTML 파싱
        soup = BeautifulSoup(html_content, "html.parser")
        body = soup.body if soup.body else soup
        
        # 1. 문서 대제목
        title_para = doc.add_paragraph()
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title_para.add_run(f"< {title} >")
        title_run.bold = True
        title_run.font.size = Pt(18)
        doc.add_paragraph() # 한 줄 띔

        # 자식 노드 순회하며 라인 분류 및 렌더링
        for child in body.children:
            if isinstance(child, str):
                text = child.strip()
                if not text:
                    continue
                p = doc.add_paragraph()
                p.add_run(text)
                continue
                
            if child.name == "br":
                doc.add_paragraph() # 빈 줄
                continue

            text = child.get_text().strip()
            html_str = str(child)
            
            if not text:
                continue

            is_scene = "***" in html_str or "***" in text

            if is_scene:
                clean_text = text.replace("***", "").strip()
                p = doc.add_paragraph()
                p.paragraph_format.space_before = Pt(14)
                p.paragraph_format.space_after = Pt(6)
                run = p.add_run(clean_text)
                run.bold = True
                run.underline = True
                continue

            # 대사 감지 (인물명: 대사)
            dialogue_match = re.match(r"^([^\s:(]+)(?:\s*\(([^)]+)\))?\s*[:：]\s*(.*)$", text)
            if not dialogue_match:
                # 탭 공백 구분 대사 감지 (예: 인물명 + 2칸 이상의 공백 + 대사)
                dialogue_match = re.match(r"^([^\s(]{1,5})(?:\s*\(([^)]+)\))?\s{2,}(.*)$", text)

            if dialogue_match:
                char_name = dialogue_match.group(1).strip()
                parenthetical = dialogue_match.group(2).strip() if dialogue_match.group(2) else None
                dialogue_text = dialogue_match.group(3).strip()

                p = doc.add_paragraph()
                p.paragraph_format.space_before = Pt(2)
                p.paragraph_format.space_after = Pt(2)
                
                # 정밀 대사 정렬: 왼쪽 여백 1.5인치, 첫 줄 내어쓰기 1.5인치
                p.paragraph_format.left_indent = Inches(1.5)
                p.paragraph_format.first_line_indent = Inches(-1.5)
                
                # 인물명 및 괄호 지문 추가
                char_run = p.add_run(char_name)
                char_run.bold = True
                if parenthetical:
                    p.add_run(f"({parenthetical})")
                
                p.add_run("\t") # 탭 문자로 대사 시작점 이동
                p.add_run(dialogue_text)
                continue

            # 일반 지문
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(4)
            p.paragraph_format.space_after = Pt(4)
            p.add_run(text)

        target = io.BytesIO()
        doc.save(target)
        target.seek(0)
        return target

    def generate_script_pdf(self, title: str, html_content: str) -> io.BytesIO:
        """대본 HTML을 파싱하여 정교한 A4 규격의 PDF 문서를 생성합니다."""
        from bs4 import BeautifulSoup
        import re
        from reportlab.platypus import Table, TableStyle, PageBreak

        logger.info(f"Generating script PDF for: {title}")
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            rightMargin=54, leftMargin=54,
            topMargin=54, bottomMargin=54
        )

        font_name = "KoreanFont" if loaded_font else "Helvetica"
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            name="ScriptTitle",
            parent=styles['Heading1'],
            fontName=font_name,
            fontSize=22,
            leading=28,
            alignment=1, # Center
            spaceAfter=25,
            textColor=colors.HexColor("#000000")
        )

        scene_style = ParagraphStyle(
            name="ScriptScene",
            parent=styles['Normal'],
            fontName=font_name,
            fontSize=11,
            leading=16,
            spaceBefore=14,
            spaceAfter=6,
            textColor=colors.HexColor("#000000")
        )

        char_style = ParagraphStyle(
            name="ScriptChar",
            parent=styles['Normal'],
            fontName=font_name,
            fontSize=10.5,
            leading=14,
            textColor=colors.HexColor("#000000")
        )

        dialogue_style = ParagraphStyle(
            name="ScriptDialogue",
            parent=styles['Normal'],
            fontName=font_name,
            fontSize=10.5,
            leading=15,
            textColor=colors.HexColor("#000000")
        )

        action_style = ParagraphStyle(
            name="ScriptAction",
            parent=styles['Normal'],
            fontName=font_name,
            fontSize=10.5,
            leading=15,
            spaceBefore=4,
            spaceAfter=4,
            textColor=colors.HexColor("#222222")
        )

        story = []

        # 1. 문서 제목
        story.append(Spacer(1, 20))
        story.append(Paragraph(f"&lt; {title} &gt;", title_style))
        story.append(Spacer(1, 15))

        # HTML 파싱
        soup = BeautifulSoup(html_content, "html.parser")
        body = soup.body if soup.body else soup

        for child in body.children:
            if isinstance(child, str):
                text = child.strip()
                if not text:
                    continue
                story.append(Paragraph(text, action_style))
                continue

            if child.name == "br":
                story.append(Spacer(1, 10))
                continue

            text = child.get_text().strip()
            html_str = str(child)

            if not text:
                continue

            is_scene = "***" in html_str or "***" in text

            if is_scene:
                clean_text = text.replace("***", "").strip()
                # 씬 헤더는 밑줄과 볼드를 적용하여 Paragraph로 렌더링
                story.append(Paragraph(f"<u><b>{clean_text}</b></u>", scene_style))
                continue

            # 대사 감지
            dialogue_match = re.match(r"^([^\s:(]+)(?:\s*\(([^)]+)\))?\s*[:：]\s*(.*)$", text)
            if not dialogue_match:
                dialogue_match = re.match(r"^([^\s(]{1,5})(?:\s*\(([^)]+)\))?\s{2,}(.*)$", text)

            if dialogue_match:
                char_name = dialogue_match.group(1).strip()
                parenthetical = dialogue_match.group(2).strip() if dialogue_match.group(2) else None
                dialogue_text = dialogue_match.group(3).strip()

                # 인물명 및 괄호 지문 구성
                char_html = f"<b>{char_name}</b>"
                if parenthetical:
                    char_html += f"<br/><font color='gray' size='9'>({parenthetical})</font>"

                char_p = Paragraph(char_html, char_style)
                dialogue_p = Paragraph(dialogue_text, dialogue_style)

                # 테두리 없는 2열 테이블로 대사 가로 정렬 (인물명 85, 대사 395)
                t = Table([[char_p, dialogue_p]], colWidths=[85, 395])
                t.setStyle(TableStyle([
                    ('VALIGN', (0,0), (-1,-1), 'TOP'),
                    ('LEFTPADDING', (0,0), (-1,-1), 0),
                    ('RIGHTPADDING', (0,0), (-1,-1), 0),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 2),
                    ('TOPPADDING', (0,0), (-1,-1), 2),
                ]))
                story.append(t)
                continue

            # 일반 지문
            story.append(Paragraph(text, action_style))

        # PDF 빌드
        doc.build(story)
        buffer.seek(0)
        return buffer
