"""
[Architecture Point: Application Layer - Service]
비즈니스 로직과 외부 서비스 오케스트레이션을 담당하는 서비스 계층입니다.
"""
import io
import logging
from uuid import UUID
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from typing import List, Dict, Any

logger = logging.getLogger(__name__)

class ExportService:
    def generate_docx(self, project: Dict[str, Any], characters: List[Dict[str, Any]], events: List[Dict[str, Any]]) -> io.BytesIO:
        logger.info(f"Executing generate_docx for project_id: {project.get('id')}...")
        try:
            doc = Document()
            
            # 1. 제목 (Title)
            title_para = doc.add_paragraph()
            title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = title_para.add_run(project.get("title", "무제 프로젝트"))
            run.bold = True
            run.font.size = Pt(24)
            
            doc.add_paragraph()
            
            # 2. 로그라인 (Logline)
            doc.add_heading("01. 로그라인", level=1)
            p_log = doc.add_paragraph()
            p_log.add_run(project.get("logline", "내용 없음")).italic = True
            p_log.paragraph_format.left_indent = Pt(20)
            
            doc.add_paragraph()

            # 3. 기획의도 (Intended Purpose)
            doc.add_heading("02. 기획의도", level=1)
            doc.add_paragraph(project.get("intended_purpose", "내용 없음"))
            
            doc.add_paragraph()

            # 4. 등장인물 (Characters)
            doc.add_heading("03. 등장인물", level=1)
            for char in characters:
                p = doc.add_paragraph(style='List Bullet')
                run = p.add_run(f"{char['name']}")
                run.bold = True
                if char.get('role'):
                    p.add_run(f" ({char['role']})")
                
                p2 = doc.add_paragraph(char.get('description', ""), style='Normal')
                p2.paragraph_format.left_indent = Pt(20)

            doc.add_paragraph()

            # 5. 전체 줄거리 (Full Synopsis)
            doc.add_heading("04. 전체 줄거리", level=1)
            doc.add_paragraph(project.get("full_synopsis", "내용 없음"))
            
            doc.add_paragraph()

            # (부록) 상세 플롯 타임라인
            doc.add_heading("별첨. 전체 플롯 타임라인", level=2)
            for event in events:
                p_ev = doc.add_paragraph()
                p_ev.add_run(f"[{event.get('time_hint', '사건')}] ").bold = True
                p_ev.add_run(event.get('title', '무제'))
                
                p_ev_content = doc.add_paragraph(event.get('content', ""))
                p_ev_content.paragraph_format.left_indent = Pt(15)

            # 푸터
            doc.add_paragraph()
            footer = doc.add_paragraph(f"Generated by Scriptly on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
            footer.alignment = WD_ALIGN_PARAGRAPH.RIGHT
            
            target = io.BytesIO()
            doc.save(target)
            target.seek(0)
            return target
        except Exception as e:
            logger.error(f"Error in generate_docx: {e}", exc_info=True)
            raise

    def generate_pdf(self, project: Dict[str, Any], characters: List[Dict[str, Any]], events: List[Dict[str, Any]]) -> io.BytesIO:
        logger.info(f"Executing generate_pdf for project_id: {project.get('id')}...")
        try:
            raise NotImplementedError("PDF export is currently under development.")
        except Exception as e:
            logger.error(f"Error in generate_pdf: {e}", exc_info=True)
            raise
